# Settings for original CMakeLists.txt as not change stuff
if( BPC_PACKAGE_FOUND )
set( VERSION "1.3.0.1" )

set(USE_DYNAMIC_LOGGING_LEVELS ON CACHE BOOL "USE_DYNAMIC_LOGGING_LEVELS" FORCE)
set(CHANGE_G3LOG_DEBUG_TO_DBUG ON CACHE BOOL "CHANGE_G3LOG_DEBUG_TO_DBUG" FORCE)
set(ENABLE_FATAL_SIGNALHANDLING OFF CACHE BOOL "ENABLE_FATAL_SIGNALHANDLING" FORCE)
set(ENABLE_VECTORED_EXCEPTIONHANDLING OFF CACHE BOOL "ENABLE_VECTORED_EXCEPTIONHANDLING" FORCE)
set(DEBUG_BREAK_AT_FATAL_SIGNAL OFF CACHE BOOL "DEBUG_BREAK_AT_FATAL_SIGNAL" FORCE)
set(G3_SHARED_LIB ON CACHE BOOL "G3_SHARED_LIB" FORCE)
set(ADD_G3LOG_UNIT_TEST OFF CACHE BOOL "ADD_G3LOG_UNIT_TEST" FORCE)
set(ADD_G3LOG_PERFORMANCE OFF CACHE BOOL "ADD_G3LOG_PERFORMANCE" FORCE)
set(ADD_FATAL_EXAMPLE OFF CACHE BOOL "ADD_FATAL_EXAMPLE" FORCE)

else()

# Platforms for which to build
set( BPC_PACKAGE_PLATFORMS "MSVC-32-14.0;MSVC-64-14.0;GNU-64-Linux-4.7.4;NISOM" )

endif()