# Info for BpcPackage framework
set( BPC_PACKAGE_NAME "g3log" )
set( BPC_VERSION "1.3.0.1" )

# Settings for original CMakeLists.txt as not change stuff
set( VERSION ${BPC_VERSION} )

set(USE_DYNAMIC_LOGGING_LEVELS ON CACHE BOOL FORCE)
set(CHANGE_G3LOG_DEBUG_TO_DBUG ON CACHE BOOL FORCE)
set(ENABLE_FATAL_SIGNALHANDLING OFF CACHE BOOL FORCE)
set(ENABLE_VECTORED_EXCEPTIONHANDLING OFF CACHE BOOL FORCE)
set(DEBUG_BREAK_AT_FATAL_SIGNAL OFF CACHE BOOL FORCE)
set(G3_SHARED_LIB ON CACHE BOOL FORCE)