macro( bpc_set_if_not_set variable value )
	if( NOT ${variable} )
		set( ${variable} "${value}" )
	endif()
endmacro()

macro( bpc_set_path_if_not_set_and_make_absolute path_variable path_value )
	bpc_set_if_not_set( ${path_variable} "${path_value}" )
	get_filename_component( ${path_variable} "${${path_variable}}" ABSOLUTE )
endmacro()

macro( bpc_if_not_defined_set variable value )
	if( NOT DEFINED ${variable} )
		set( ${variable} "${value}" )
	endif()
endmacro()

function( bpc_list_intersect return left right )
	set( intersection )
	foreach( item ${left} )
		list( FIND right ${item} index )
		if( NOT (index EQUAL -1) )
			list( APPEND intersection ${item} )
		endif()
	endforeach()
	set( ${return} ${intersection} PARENT_SCOPE )
endfunction()

function( bpc_list_unite return left right )
	set( union ${left} )
	foreach( item ${right} )
		list( FIND left ${item} index )
		if( index EQUAL -1 )
			list( APPEND union ${item} )
		endif()
	endforeach()
	set( ${return} ${union} PARENT_SCOPE )
endfunction()

function( bpc_list_subtract return left right )
	set( difference )
	foreach( item ${left} )
		list( FIND right ${item} index )
		if( index EQUAL -1 )
			list( APPEND difference ${item} )
		endif()
	endforeach()
	set( ${return} ${difference} PARENT_SCOPE )
endfunction()